name: check and update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
        
      - name: 下载工件
        uses: actions/download-artifact@v4
        with:
          name: digest
        continue-on-error: true

      - name: 检查astrbot镜像
        id: check
        run: |
          DIGEST_ASTRBOT_NEW=$(curl -s "https://hub.docker.com/v2/namespaces/soulter/repositories/astrbot/tags/latest" | jq -r '.images[] | select(.architecture == "arm64") | .digest')
          DIGEST_ASTRBOT_OLD=$(cat astrbot.txt 2>/dev/null || echo "")

          echo "digest_new=$DIGEST_ASTRBOT_NEW" >> "$GITHUB_OUTPUT"
          echo "digest_old=$DIGEST_ASTRBOT_OLD" >> "$GITHUB_OUTPUT"
          echo "$DIGEST_ASTRBOT_NEW" > astrbot.txt

      - name: 若不一致则更新
        if: ${{ steps.check.outputs.digest_new != steps.check.outputs.digest_old }}
        uses: ./.github/workflows/astrbot_paywright.yml

      - name: 更新工件
        if: ${{ steps.check.outputs.digest_new != steps.check.outputs.digest_old }}
        uses: actions/upload-artifact@v4 
        with:
          name: digest
          path: astrbot.txt
