name: Build noname

on:
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取源码
        uses: actions/checkout@v6
        with:
          repository: 'libnoname/noname'

      - name: 构建文件
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
      - run: |
          curl -L https://raw.githubusercontent.com/qihang518887/mayin_use/refs/heads/main/noname/Dockerfile > Dockerfile
          curl -L https://raw.githubusercontent.com/qihang518887/mayin_use/refs/heads/main/noname/tsup.config.ts > tsup.config.ts          
          npm install -g pnpm
          pnpm install
          pnpm build
        working-directory: ./packages/server

      - name: 登录Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: ./packages/server
          platforms: linux/amd64,linux/arm64
          push: true
          tags: mayin/noname-server
